language: scala
scala:
  - 2.9.2
  - 2.9.3
  - 2.10.0
  - 2.10.1
  - 2.10.4
  - 2.11.0
jdk:
  - oraclejdk7

install: /bin/true
script: ./sbt -J-Xss1M -J-XX:MaxPermSize=256M ";++${TRAVIS_SCALA_VERSION};clean;compile;test"
